
service: stellar-room-wallet
app: stellar-room-wallet
org: tyvdh

plugins:
  - serverless-finch
  - serverless-webpack
  - serverless-offline

custom:
  client:
    bucketName: stellar-room-wallet
    errorDocument: 200.html
    distributionFolder: dist
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn
  serverless-offline:
    httpsProtocol: certs
    port: 4000

provider:
  name: aws
  runtime: nodejs10.x
  environment: ${file(env.yml)}
  tracing:
    lambda: true

functions:
  pusherAuth:
    handler: handler.auth
    timeout: 10
    events:
      - http:
          path: pusher/auth
          method: POST
          cors: true